# Generated by Django 4.2.6 on 2023-11-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
